// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package flowexecmock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/thunder-id/thunderid/internal/flow/core"
)

// newFlowGraphResolverMock creates a new instance of flowGraphResolverMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newFlowGraphResolverMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *flowGraphResolverMock {
	mock := &flowGraphResolverMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// flowGraphResolverMock is an autogenerated mock type for the flowGraphResolver type
type flowGraphResolverMock struct {
	mock.Mock
}

type flowGraphResolverMock_Expecter struct {
	mock *mock.Mock
}

func (_m *flowGraphResolverMock) EXPECT() *flowGraphResolverMock_Expecter {
	return &flowGraphResolverMock_Expecter{mock: &_m.Mock}
}

// ResolveFlowGraph provides a mock function for the type flowGraphResolverMock
func (_mock *flowGraphResolverMock) ResolveFlowGraph(ctx context.Context, flowID string) (core.GraphInterface, error) {
	ret := _mock.Called(ctx, flowID)

	if len(ret) == 0 {
		panic("no return value specified for ResolveFlowGraph")
	}

	var r0 core.GraphInterface
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (core.GraphInterface, error)); ok {
		return returnFunc(ctx, flowID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) core.GraphInterface); ok {
		r0 = returnFunc(ctx, flowID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.GraphInterface)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, flowID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// flowGraphResolverMock_ResolveFlowGraph_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveFlowGraph'
type flowGraphResolverMock_ResolveFlowGraph_Call struct {
	*mock.Call
}

// ResolveFlowGraph is a helper method to define mock.On call
//   - ctx context.Context
//   - flowID string
func (_e *flowGraphResolverMock_Expecter) ResolveFlowGraph(ctx interface{}, flowID interface{}) *flowGraphResolverMock_ResolveFlowGraph_Call {
	return &flowGraphResolverMock_ResolveFlowGraph_Call{Call: _e.mock.On("ResolveFlowGraph", ctx, flowID)}
}

func (_c *flowGraphResolverMock_ResolveFlowGraph_Call) Run(run func(ctx context.Context, flowID string)) *flowGraphResolverMock_ResolveFlowGraph_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *flowGraphResolverMock_ResolveFlowGraph_Call) Return(graphInterface core.GraphInterface, err error) *flowGraphResolverMock_ResolveFlowGraph_Call {
	_c.Call.Return(graphInterface, err)
	return _c
}

func (_c *flowGraphResolverMock_ResolveFlowGraph_Call) RunAndReturn(run func(ctx context.Context, flowID string) (core.GraphInterface, error)) *flowGraphResolverMock_ResolveFlowGraph_Call {
	_c.Call.Return(run)
	return _c
}
